[package]
name = "zls"
version = "0.16.0"
revision = 3
description = "A language server for Zig supporting developers with features like autocomplete and goto definition"
license = "MIT"
homepage = "https://zigtools.org/zls/install/"

[source]
repo = "zigtools/zls"
url = "https://github.com/zigtools/zls/archive/refs/tags/0.16.0.tar.gz"
sha256 = "e7c5936f5b3a057ce851be0876e4e259b5c4d02f9aae038cd24a5d6b586b029f"
released_at = "2026-04-16"

[build]
system = "zig"
steps = [
  "zig build -Doptimize=ReleaseSafe -Dcpu=baseline --prefix ${PREFIX}",
]

[dependencies]
build = ["zig"]