[package]
name = "zls"
version = "0.15.1"
description = "A language server for Zig supporting developers with features like autocomplete and goto definition"
license = "MIT"
homepage = "https://zigtools.org/zls/install/"

[source]
repo = "zigtools/zls"
url = "https://github.com/zigtools/zls/archive/refs/tags/0.15.1.tar.gz"
sha256 = "40a4559c3007ed9333769fc3e111ed466403b53f31ad9242874a62ab385b331b"
released_at = "2025-01-15"

[build]
system = "zig"
steps = [
  "zig build -Doptimize=ReleaseSafe --prefix ${PREFIX}",
]

[dependencies]
build = ["zig"]