[package]
name = "openssl"
version = "4.0.0"
revision = 2
description = "Cryptography and SSL/TLS Toolkit"
license = "Apache-2.0"
homepage = "https://openssl-library.org"

[source]
repo = "openssl/openssl"
url = "https://github.com/openssl/openssl/releases/download/openssl-4.0.0/openssl-4.0.0.tar.gz"
sha256 = "c32cf49a959c4f345f9606982dd36e7d28f7c58b19c2e25d75624d2b3d2f79ac"

[build.darwin-arm64]
steps = [
  "perl ./Configure --prefix=${PREFIX} --openssldir=${PREFIX}/etc/openssl --libdir=lib no-ssl3 no-ssl3-method no-zlib enable-ec_nistp_64_gcc_128 darwin64-arm64-cc",
  "make -j${JOBS}",
  "make install MANDIR=${PREFIX}/share/man MANSUFFIX=ssl",
]

[build.linux-amd64]
steps = [
  "perl ./Configure --prefix=${PREFIX} --openssldir=${PREFIX}/etc/openssl --libdir=lib no-ssl3 no-ssl3-method no-zlib linux-x86_64",
  "make -j${JOBS}",
  "make install MANDIR=${PREFIX}/share/man MANSUFFIX=ssl",
]

[build.linux-arm64]
steps = [
  "perl ./Configure --prefix=${PREFIX} --openssldir=${PREFIX}/etc/openssl --libdir=lib no-ssl3 no-ssl3-method no-zlib linux-aarch64",
  "make -j${JOBS}",
  "make install MANDIR=${PREFIX}/share/man MANSUFFIX=ssl",
]
