[package]
name = "openjpeg"
version = "2.5.4"
platforms = ["darwin-amd64", "darwin-arm64"]
description = "JPEG 2000 image codec"
license = "BSD-2-Clause"
homepage = "https://www.openjpeg.org/"

[source]
repo = "uclouvain/openjpeg"
url = "https://github.com/uclouvain/openjpeg/archive/refs/tags/v2.5.4.tar.gz"
sha256 = "a695fbe19c0165f295a8531b1e4e855cd94d0875d2f88ec4b61080677e27188a"

[build]
steps = [
  "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DBUILD_CODEC=ON -DBUILD_DOC=OFF -DBUILD_TESTING=OFF",
  "cmake --build build -j ${JOBS}",
  "cmake --install build",
]

[dependencies]
build = ["cmake", "libpng", "libtiff", "pkgconf"]
runtime = ["libpng", "libtiff"]
