version = "0.7.1-2"

[darwin-arm64]
sha256 = "245848efb7932557101634bd41c0e045f23a4c37c866c3bb2b75cbaa802f477c"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-amd64]
sha256 = "38cca39b4f16ca9ab3f10d363acfea52dbffa519a749d642d0880000dddad5fd"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-arm64]
sha256 = "ec90e17665850c48c70089103e0ae3eb75fcf9bd1e1884ae5a8eda06f9cb52b2"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]
