version = "1.18.4-2"

[darwin-arm64]
sha256 = "58b9e7400a55eb327a3ad68803559bb2a4f062b04a57f06f9c01ee21930a176b"
manifest_digest = "sha256:5840d5f51b5b0148cfdd74d90353d165c38c933ddb9ed7da13c954a26308ee17"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "expat", version = "2.7.5", revision = 2 },
  { name = "fontconfig", version = "2.17.1", revision = 2 },
  { name = "freetype", version = "2.14.3", revision = 2 },
  { name = "gnumake", version = "4.4.1", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "libpng", version = "1.6.58", revision = 2 },
  { name = "meson", version = "1.11.1", revision = 3 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "ninja", version = "1.13.2", revision = 3 },
  { name = "openssl", version = "3.6.1", revision = 4 },
  { name = "pixman", version = "0.46.4", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "python", version = "3.14.5", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 3 },
]

[[history]]
version = "1.18.4-2"
darwin-arm64 = { sha256 = "58b9e7400a55eb327a3ad68803559bb2a4f062b04a57f06f9c01ee21930a176b", manifest_digest = "sha256:5840d5f51b5b0148cfdd74d90353d165c38c933ddb9ed7da13c954a26308ee17" }
