[package]
name = "cmake"
version = "4.3.1"
description = "Cross-platform build system generator"
license = "BSD-3-Clause"
homepage = "https://cmake.org"

[source]
repo = "Kitware/CMake"
url = "https://github.com/Kitware/CMake/releases/download/v4.3.1/cmake-4.3.1.tar.gz"
sha256 = "0798f4be7a1a406a419ac32db90c2956936fecbf50db3057d7af47d69a2d7edb"

[build]
steps = [
  "./bootstrap --prefix=${PREFIX} --parallel=${JOBS} -- -DCMAKE_USE_OPENSSL=OFF",
  "make -j${JOBS}",
  "make install",
]

[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/cmake/blobs/sha256:8e39276b15f1ac64d8985b14f17383bc4f0234fe453d74f6bfe6d218e49fa381"
sha256 = "8e39276b15f1ac64d8985b14f17383bc4f0234fe453d74f6bfe6d218e49fa381"

[binary.linux-amd64]
url = "https://ghcr.io/v2/kelp/gale-recipes/cmake/blobs/sha256:39b2659a1f5458ea3846d1cc597cd2f3dcc2006d3febc73f5193af31e97ab095"
sha256 = "39b2659a1f5458ea3846d1cc597cd2f3dcc2006d3febc73f5193af31e97ab095"
