version = "3.2.4-2"

[darwin-arm64]
sha256 = "c347a597799b5e78e76c3d0aecbfb217f1c18007ebebf1e6ecd3093a02a3628a"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-amd64]
sha256 = "3ed293bb1fa57633eece0234a29d22a58e4964a2391d156e5e0c0ce703308c51"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-arm64]
sha256 = "93a4a469c3c3f5630af4d9d40c86dff1f72486ec89fc74d28478b034d9223adf"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]
