version = "8.6.3-2"

[darwin-arm64]
sha256 = "646d94265d2f5554c245a191c6c61dacd650f949bbc33616ffc6fd08f0eb8151"
deps = [
  { name = "gnumake", version = "4.4.1", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
]

[linux-amd64]
sha256 = "7752949e9df1fb5ba5b977ff4eb1d659efbbb711df71b3167ebb43b542218a0a"
deps = [
  { name = "gnumake", version = "4.4.1", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
]

[linux-arm64]
sha256 = "bc992fdea76d1a02f0d9c2cdaa8a5cff5aca2a49842d8c55190a499e60ca8d00"
deps = [
  { name = "gnumake", version = "4.4.1", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
]
