[package]
name = "redis"
version = "8.8.0"
revision = 2
description = "Persistent key-value database, with built-in net interface"
license = "AGPL-3.0-only"
homepage = "https://redis.io/"

[source]
repo = "redis/redis"
url = "https://download.redis.io/releases/redis-8.8.0.tar.gz"
sha256 = "88422181efb0c9c0abba332e3e391d409e1e13714b838931669235e5796f704b"
released_at = "2026-05-25"

[build]
steps = [
  "make -C src -j${JOBS} BUILD_TLS=yes redis-server redis-cli redis-benchmark redis-check-rdb redis-check-aof",
  "install -d ${PREFIX}/bin",
  "install src/redis-server ${PREFIX}/bin/redis-server",
  "install src/redis-cli ${PREFIX}/bin/redis-cli",
  "install src/redis-benchmark ${PREFIX}/bin/redis-benchmark",
  "ln -sf redis-server ${PREFIX}/bin/redis-check-rdb",
  "ln -sf redis-server ${PREFIX}/bin/redis-check-aof",
  "ln -sf redis-server ${PREFIX}/bin/redis-sentinel",
]

[dependencies]
build = ["gnumake"]
runtime = ["openssl"]
