[package]
name = "rsync"
version = "3.5.0"
revision = 2
description = "Utility that provides fast incremental file transfer"
license = "GPL-3.0-or-later"
homepage = "https://rsync.samba.org/"

[source]
repo = "RsyncProject/rsync"
url = "https://download.samba.org/pub/rsync/src/rsync-3.5.0.tar.gz"
sha256 = "c7ffd1ef653e99540f661e47cb00b7f9cad1ee6b972399b16f93d672656e0d33"
released_at = "2026-08-13"

[build]
steps = [
  "./configure --prefix=${PREFIX} --disable-lz4 --disable-xxhash",
  "make -j${JOBS}",
  "make install",
]

[dependencies]
build = ["pkgconf"]
runtime = ["openssl", "zstd"]
