[package]
name = "yt-dlp"
version = "2026.03.17"
revision = 3
description = "A feature-rich command-line audio/video downloader"
license = "Unlicense"
homepage = "https://github.com/yt-dlp/yt-dlp"

[source]
repo = "yt-dlp/yt-dlp"
url = "https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2026.03.17.tar.gz"
sha256 = "924483986441d8a1e669a0e4371d753a9256ce4bdc06032394ccb7b793342434"
released_at = "2025-01-27"

[dependencies]
build = ["python"]

[build]
system = "python"
steps = [
  "${DEP_PYTHON}/bin/python3 -m pip install --prefix=${PREFIX} --no-deps .",
]