[package]
name = "yt-dlp"
version = "2026.07.04"
revision = 3
description = "A feature-rich command-line audio/video downloader"
license = "Unlicense"
homepage = "https://github.com/yt-dlp/yt-dlp"

[source]
repo = "yt-dlp/yt-dlp"
url = "https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2026.07.04.tar.gz"
sha256 = "7fb7ca0509dd8f21263246d3d749a346e049fa9d3cfdef072e05c7bbd88d6fc0"
released_at = "2026-07-04"

[dependencies]
build = ["python"]

[build]
system = "python"
steps = [
  "${DEP_PYTHON}/bin/python3 -m pip install --prefix=${PREFIX} --no-deps .",
]