version = "2.61.0-2"

[darwin-arm64]
sha256 = "06db7aa5af904c9c6e51e0175ebbb2848d4ef25a53f6a0de7e718f3df4d97ebf"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
]

[linux-amd64]
sha256 = "4b9fe5d6f3c98e8e9900d457d40e148a25629726e008b2495b8dd342a812f8ef"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
]

[linux-arm64]
sha256 = "53aad6854388573b1002225417902ceec5859032040b15f6acf3c1f7be482f5f"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
]
