version = "4.7.1-2"

[darwin-arm64]
sha256 = "e41c8617b529e06db5bd3f480af95acbd3c8606de53602a645512d1349cbf181"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
]

[linux-amd64]
sha256 = "da36be9eed7d54432032e366d4e92283cc53aae5d92592bf31b6d1aa31ae25a8"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
]

[linux-arm64]
sha256 = "386cb9c6c1248e27acf7248fbed89c04f8f4929a3b27b0dba67f81063d405011"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
]
