[package]
name = "flyctl"
version = "0.4.59"
revision = 2
description = "Command line tools for fly.io services"
license = "Apache-2.0"
homepage = "https://fly.io"

[source]
repo = "superfly/flyctl"
url = "https://github.com/superfly/flyctl/archive/refs/tags/v0.4.59.tar.gz"
sha256 = "3236cdb1535b1a2051a9f1f198a9f6d481416638ef5aadd2ab0d3a8f86471656"
released_at = "2026-06-09"

[build]
system = "go"
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go generate ./...",
  "CGO_ENABLED=0 go build -o ${PREFIX}/bin/flyctl -ldflags=\"-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")' -X 'github.com/superfly/flyctl/internal/buildinfo.branchName=main'\" .",
]

[dependencies]
build = ["go"]