[package]
name = "direnv"
version = "2.37.1"
description = "Per-directory environment variables"
license = "MIT"
homepage = "https://direnv.net"

[source]
repo = "direnv/direnv"
url = "https://github.com/direnv/direnv/archive/refs/tags/v2.37.1.tar.gz"
sha256 = "4142fbb661f3218913fac08d327c415e87b3e66bd0953185294ff8f3228ead24"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -o ${PREFIX}/bin/direnv",
]





[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/direnv/blobs/sha256:29f3e921a0a02ea18722cbe8f2d7c0ef73239f99764b2b25dd31363eab32e701"
sha256 = "29f3e921a0a02ea18722cbe8f2d7c0ef73239f99764b2b25dd31363eab32e701"
