[package]
name = "doctl"
version = "1.160.0"
revision = 2
description = "Command-line tool for DigitalOcean"
license = "Apache-2.0"
homepage = "https://github.com/digitalocean/doctl"

[source]
repo = "digitalocean/doctl"
url = "https://github.com/digitalocean/doctl/archive/refs/tags/v1.160.0.tar.gz"
sha256 = "dd5be822f0ec4a55d418f14acbccd2a4e127c514dfade78224fbd003309b57c9"
released_at = "2026-05-26"

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -o ${PREFIX}/bin/doctl ./cmd/doctl",
]

[dependencies]
build = ["go"]
