[package]
name = "doggo"
version = "1.2.0"
revision = 2
description = "Command-line DNS Client for Humans"
license = "GPL-3.0-or-later"
homepage = "https://doggo.mrkaran.dev/"

[source]
repo = "mr-karan/doggo"
url = "https://github.com/mr-karan/doggo/archive/refs/tags/v1.2.0.tar.gz"
sha256 = "ddea7da5f8e6263626ffbff57e3df5e84df4343a740b2f7a8dae2505aae645d9"

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -o ${PREFIX}/bin/doggo ./cmd/doggo",
]

[dependencies]
build = ["go"]
