[package]
name = "dtc"
version = "1.7.2"
revision = 1
description = "Device Tree Compiler (dtc) and libfdt"
license = "GPL-2.0-or-later OR BSD-2-Clause"
homepage = "https://git.kernel.org/pub/scm/utils/dtc/dtc.git"

[source]
repo = "dgibson/dtc"
url = "https://github.com/dgibson/dtc/archive/refs/tags/v1.7.2.tar.gz"
sha256 = "8f1486962f093f28a2f79f01c1fd82f144ef640ceabe555536d43362212ceb7c"
released_at = "2024-04-21"

[build]
steps = [
  "make NO_PYTHON=1 NO_YAML=1 NO_VALGRIND=1 EXTRA_CFLAGS=-Wno-error PREFIX=${PREFIX} -j${JOBS}",
  "make NO_PYTHON=1 NO_YAML=1 NO_VALGRIND=1 EXTRA_CFLAGS=-Wno-error PREFIX=${PREFIX} install",
]

