[package]
name = "dtc"
version = "1.8.1"
revision = 1
description = "Device Tree Compiler (dtc) and libfdt"
license = "GPL-2.0-or-later OR BSD-2-Clause"
homepage = "https://git.kernel.org/pub/scm/utils/dtc/dtc.git"

[source]
repo = "dgibson/dtc"
url = "https://github.com/dgibson/dtc/archive/refs/tags/v1.8.1.tar.gz"
sha256 = "74b50bb19134f6562490afea53e59953dd6c4afb17e5ccb60be32221262d3390"
released_at = "2026-05-28"

[build]
steps = [
  "make NO_PYTHON=1 NO_YAML=1 NO_VALGRIND=1 EXTRA_CFLAGS=-Wno-error PREFIX=${PREFIX} -j${JOBS}",
  "make NO_PYTHON=1 NO_YAML=1 NO_VALGRIND=1 EXTRA_CFLAGS=-Wno-error PREFIX=${PREFIX} install",
]

