[package]
name = "socat"
version = "1.8.1.1"
description = "SOcket CAT: netcat on steroids"
license = "GPL-2.0-only"
homepage = "http://www.dest-unreach.org/socat/"

[source]
url = "http://www.dest-unreach.org/socat/download/socat-1.8.1.1.tar.gz"
sha256 = "f68b602c80e94b4b7498d74ec408785536fe33534b39467977a82ab2f7f01ddb"

[build]
steps = [
  "./configure --prefix=${PREFIX} --disable-readline",
  "make -j${JOBS}",
  "make install",
]

[dependencies]
build = ["pkgconf"]
runtime = ["openssl"]
