version = "1.25.1-2"

[darwin-arm64]
sha256 = "63c579772955ab7814ae324cc5482af7f89c7d86f3b5520340ba04a3c8c5bd0f"
manifest_digest = "sha256:f316b09e90ca79cfa0072cec34905ff9c440094f62bba067a6f9033145bee9db"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "dbus", version = "1.16.2", revision = 3 },
  { name = "expat", version = "2.7.5", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "meson", version = "1.11.1", revision = 3 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "ninja", version = "1.13.2", revision = 3 },
  { name = "openssl", version = "3.6.1", revision = 4 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "python", version = "3.14.5", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "rust", version = "1.96.0", revision = 1 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 3 },
]

[linux-amd64]
sha256 = "dce7d653af9ba956aca77110522b3225a4da06d124e27d98d6fa9267a81985cb"
manifest_digest = "sha256:2663d6637645b90fadbbe1a294a9011d3de849360cc1fa5a4b62f5d922944aab"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "dbus", version = "1.16.2", revision = 3 },
  { name = "expat", version = "2.7.5", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "meson", version = "1.11.1", revision = 3 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "ninja", version = "1.13.2", revision = 3 },
  { name = "openssl", version = "3.6.1", revision = 4 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "python", version = "3.14.5", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "rust", version = "1.96.0", revision = 1 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 3 },
]

[linux-arm64]
sha256 = "8bede92edfac58d96e33d58a9aa6f2f2ef7781a242a5030380ac39826863fa27"
manifest_digest = "sha256:8e58f28180f6854e93f87b434d9af8fe2e95a37ed28522dc18723509ca652dec"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "dbus", version = "1.16.2", revision = 3 },
  { name = "expat", version = "2.7.5", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "meson", version = "1.11.1", revision = 3 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "ninja", version = "1.13.2", revision = 3 },
  { name = "openssl", version = "3.6.1", revision = 4 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "python", version = "3.14.5", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "rust", version = "1.96.0", revision = 1 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 3 },
]

[[history]]
version = "1.25.1-2"
darwin-arm64 = { sha256 = "63c579772955ab7814ae324cc5482af7f89c7d86f3b5520340ba04a3c8c5bd0f", manifest_digest = "sha256:f316b09e90ca79cfa0072cec34905ff9c440094f62bba067a6f9033145bee9db" }
linux-amd64 = { sha256 = "dce7d653af9ba956aca77110522b3225a4da06d124e27d98d6fa9267a81985cb", manifest_digest = "sha256:2663d6637645b90fadbbe1a294a9011d3de849360cc1fa5a4b62f5d922944aab" }
linux-arm64 = { sha256 = "8bede92edfac58d96e33d58a9aa6f2f2ef7781a242a5030380ac39826863fa27", manifest_digest = "sha256:8e58f28180f6854e93f87b434d9af8fe2e95a37ed28522dc18723509ca652dec" }
