[package]
name = "statix"
version = "0.5.8"
revision = 2
description = "Lints and suggestions for the Nix programming language"
license = "MIT"
homepage = "https://github.com/oppiliappan/statix"

[source]
repo = "oppiliappan/statix"
url = "https://github.com/oppiliappan/statix/archive/refs/tags/v0.5.8.tar.gz"
sha256 = "547ee83df5814c18f8577b5ca25a1f12a416900b6eaa95821386a28090e8a89d"
released_at = "2025-01-15"

[build]
system = "cargo"
steps = [
  "cargo install --locked --path bin --root ${PREFIX}",
]

[dependencies]
build = ["rust"]