[package]
name = "wget"
version = "1.25.0"
revision = 3
description = "Internet file retriever"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/wget/"

[source]
repo = "mirror/wget"
url = "https://ftpmirror.gnu.org/gnu/wget/wget-1.25.0.tar.gz"
sha256 = "766e48423e79359ea31e41db9e5c289675947a7fcf2efdcedb726ac9d0da3784"
released_at = "2024-11-10"

[build]
steps = [
  "./configure --prefix=${PREFIX} --with-ssl=openssl --disable-debug",
  "make -j${JOBS}",
  "make install",
]

[dependencies]
build = ["pkgconf"]
runtime = ["openssl", "libidn2", "gettext"]
