[package]
name = "patchelf"
version = "0.18.0"
description = "Modify ELF executables and libraries"
license = "GPL-3.0"
homepage = "https://github.com/NixOS/patchelf"

[source]
repo = "NixOS/patchelf"
url = "https://github.com/NixOS/patchelf/releases/download/0.18.0/patchelf-0.18.0.tar.gz"
sha256 = "64de10e4c6b8b8379db7e87f58030f336ea747c0515f381132e810dbf84a86e7"

[build]
steps = [
  "./configure --prefix=${PREFIX}",
  "make -j${JOBS}",
  "make install",
]

[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/patchelf/blobs/sha256:d823c694a45399bb241608a1514acec8b842df4b31421acb0aa9fa45985e0aec"
sha256 = "d823c694a45399bb241608a1514acec8b842df4b31421acb0aa9fa45985e0aec"
