[package]
name = "patchelf"
version = "0.18.0"
revision = 2
description = "Modify ELF executables and libraries"
license = "GPL-3.0"
homepage = "https://github.com/NixOS/patchelf"

[source]
repo = "NixOS/patchelf"
url = "https://github.com/NixOS/patchelf/releases/download/0.18.0/patchelf-0.18.0.tar.gz"
sha256 = "64de10e4c6b8b8379db7e87f58030f336ea747c0515f381132e810dbf84a86e7"

[build]
steps = [
  "./configure --prefix=${PREFIX}",
  "make -j${JOBS}",
  "make install",
]
