[package]
name = "pkgconf"
version = "2.5.1"
description = "Package compiler and linker metadata toolkit"
license = "ISC"
homepage = "http://pkgconf.org"

[source]
url = "https://distfiles.ariadne.space/pkgconf/pkgconf-2.5.1.tar.gz"
sha256 = "ab89d59810d9cad5dfcd508f25efab8ea0b1c8e7bad91c2b6351f13e6a5940d8"

[build]
steps = [
  "./configure --prefix=${PREFIX} --disable-shared --enable-static",
  "make -j${JOBS}",
  "make install",
  "ln -sf pkgconf ${PREFIX}/bin/pkg-config",
]

[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/pkgconf/blobs/sha256:5d9da219e1ecca3ed606d1b2a1efbedc3ede1b793728e721afde43b4492747f3"
sha256 = "5d9da219e1ecca3ed606d1b2a1efbedc3ede1b793728e721afde43b4492747f3"
