[package]
name = "podman"
version = "5.8.2"
revision = 2
platforms = ["linux-amd64", "linux-arm64"]
description = "Tool for managing OCI containers and pods"
license = "Apache-2.0 AND GPL-3.0-or-later"
homepage = "https://podman.io/"

[source]
repo = "containers/podman"
url = "https://github.com/containers/podman/archive/refs/tags/v5.8.2.tar.gz"
sha256 = "b20ea65afc5a58ea1cea019bd51a5d84eb9042d25d3eb82c55010c8815732d84"

[build]
steps = [
  "make PREFIX=${PREFIX} HELPER_BINARIES_DIR=${PREFIX}/libexec/podman BUILDTAGS=\"exclude_graphdriver_btrfs btrfs_noversion containers_image_openpgp\"",
  "make install PREFIX=${PREFIX} HELPER_BINARIES_DIR=${PREFIX}/libexec/podman",
]

[dependencies]
build = ["go", "gnumake"]
