[package]
name = "podman"
version = "6.0.2"
revision = 2
platforms = ["linux-amd64", "linux-arm64"]
description = "Tool for managing OCI containers and pods"
license = "Apache-2.0 AND GPL-3.0-or-later"
homepage = "https://podman.io/"

[source]
repo = "containers/podman"
url = "https://github.com/containers/podman/archive/refs/tags/v6.0.2.tar.gz"
sha256 = "0895a541aeb7aa8e99133ed2b328c1bb40fd397b7c3b01e083396c90e8628756"

[build]
steps = [
  "make PREFIX=${PREFIX} HELPER_BINARIES_DIR=${PREFIX}/libexec/podman BUILDTAGS=\"exclude_graphdriver_btrfs btrfs_noversion containers_image_openpgp\"",
  "make install PREFIX=${PREFIX} HELPER_BINARIES_DIR=${PREFIX}/libexec/podman",
]

[dependencies]
build = ["go", "gnumake"]
