[package]
name = "podman"
version = "5.8.3"
revision = 2
platforms = ["linux-amd64", "linux-arm64"]
description = "Tool for managing OCI containers and pods"
license = "Apache-2.0 AND GPL-3.0-or-later"
homepage = "https://podman.io/"

[source]
repo = "containers/podman"
url = "https://github.com/containers/podman/archive/refs/tags/v5.8.3.tar.gz"
sha256 = "c54a2ec4b4fb5577288992aaa78684397ec3552fb2d1234d910ec50097d05c0f"

[build]
steps = [
  "make PREFIX=${PREFIX} HELPER_BINARIES_DIR=${PREFIX}/libexec/podman BUILDTAGS=\"exclude_graphdriver_btrfs btrfs_noversion containers_image_openpgp\"",
  "make install PREFIX=${PREFIX} HELPER_BINARIES_DIR=${PREFIX}/libexec/podman",
]

[dependencies]
build = ["go", "gnumake"]
