version = "34.1-2"

[darwin-arm64]
sha256 = "e1d6b00da23573fe68786d08acce6f5b97ff88f2920a67d5b928a0c170a45ab0"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
]

[linux-amd64]
sha256 = "b657cf9e0b2718333c0b2c43f7195878bb55cadb18fff178b7e91b6ca54a233a"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
]

[linux-arm64]
sha256 = "21c37bae69ea44a21468118d1bfbd6d6d7496c061d7b47b86207cbf4a9e8729d"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
]
