[package]
name = "terraform"
version = "1.15.7"
revision = 2
description = "Tool to build, change, and version infrastructure"
license = "MPL-2.0"
homepage = "https://www.terraform.io/"

[source]
repo = "hashicorp/terraform"
url = "https://github.com/hashicorp/terraform/archive/refs/tags/v1.15.7.tar.gz"
sha256 = "1b2904281ec8746a1ba2fa9ebeadbcb1f73d306cc31cdef2f08857f9d2f7f3b1"

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -o ${PREFIX}/bin/terraform",
]

[dependencies]
build = ["go"]
