version = "3.9-2"

[darwin-arm64]
sha256 = "9085d20bd34420235f277eed03f8fd54908b94ecc27bc36722dfd7fd37bc02f9"
manifest_digest = "sha256:8a3a31a7fe6136f723221f3f6274a88dcb5bdcabc1815f7103a951c836a9722d"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "gettext", version = "1.0", revision = 2 },
  { name = "glib", version = "2.88.1", revision = 9 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "lua", version = "5.5.0", revision = 5 },
  { name = "meson", version = "1.11.1", revision = 3 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "ninja", version = "1.13.2", revision = 3 },
  { name = "openssl", version = "3.6.1", revision = 4 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "python", version = "3.14.5", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 3 },
]

[linux-amd64]
sha256 = "b607053799541f5853af4461639de7976f4b46568d0ffe6db077b572cc1aa2b5"
manifest_digest = "sha256:fc80076ce7af4b893576150c33b44bb6f0f0d25f9fcb3bc87e8534ec8a72191e"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "gettext", version = "1.0", revision = 2 },
  { name = "glib", version = "2.88.1", revision = 9 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "lua", version = "5.5.0", revision = 5 },
  { name = "meson", version = "1.11.1", revision = 3 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "ninja", version = "1.13.2", revision = 3 },
  { name = "openssl", version = "3.6.1", revision = 4 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "python", version = "3.14.5", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 3 },
]

[linux-arm64]
sha256 = "feaa98671bc3c47c8e511af2829ca59c747b14e379c6dc8f97bc308606608a63"
manifest_digest = "sha256:00492c2e77e3d8d6fbf24cbd0e056b7c42a8cbc33b5a32a1d3dcb672eab539c0"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "gettext", version = "1.0", revision = 2 },
  { name = "glib", version = "2.88.1", revision = 9 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "lua", version = "5.5.0", revision = 5 },
  { name = "meson", version = "1.11.1", revision = 3 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "ninja", version = "1.13.2", revision = 3 },
  { name = "openssl", version = "3.6.1", revision = 4 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "python", version = "3.14.5", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 3 },
]

[[history]]
version = "3.9-2"
darwin-arm64 = { sha256 = "9085d20bd34420235f277eed03f8fd54908b94ecc27bc36722dfd7fd37bc02f9", manifest_digest = "sha256:8a3a31a7fe6136f723221f3f6274a88dcb5bdcabc1815f7103a951c836a9722d" }
linux-amd64 = { sha256 = "b607053799541f5853af4461639de7976f4b46568d0ffe6db077b572cc1aa2b5", manifest_digest = "sha256:fc80076ce7af4b893576150c33b44bb6f0f0d25f9fcb3bc87e8534ec8a72191e" }
linux-arm64 = { sha256 = "feaa98671bc3c47c8e511af2829ca59c747b14e379c6dc8f97bc308606608a63", manifest_digest = "sha256:00492c2e77e3d8d6fbf24cbd0e056b7c42a8cbc33b5a32a1d3dcb672eab539c0" }
