[package]
name = "ninja"
version = "1.13.2"
revision = 2
description = "A small build system with a focus on speed"
license = "Apache-2.0"
homepage = "https://ninja-build.org/"

[source]
repo = "ninja-build/ninja"
url = "https://github.com/ninja-build/ninja/archive/refs/tags/v1.13.2.tar.gz"
sha256 = "974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17"
released_at = "2025-11-20"

[build]
steps = [
  "python3 configure.py --bootstrap",
  "mkdir -p ${PREFIX}/bin",
  "cp ninja ${PREFIX}/bin/",
]

[dependencies]
build = ["python"]