[package]
name = "nodejs"
version = "26.3.0"
revision = 2
description = "Open-source, cross-platform JavaScript runtime environment"
license = "MIT"
homepage = "https://nodejs.org/"

[source]
repo = "nodejs/node"
url = "https://nodejs.org/dist/v26.3.0/node-v26.3.0.tar.xz"
sha256 = "319ad5d7d20cc622e55eb75b9f1a2546b77a08bd462b67030d0c89316c2c2349"

[build]
steps = [
  "./configure --prefix=${PREFIX}",
  "make -j${JOBS}",
  "make install",
]

[dependencies]
build = []
