version = "12.3.2-2"

[darwin-arm64]
sha256 = "68f9d491333dda9ef85964867c8b09988e73b25951f6dd7e52842927e5525c8c"
deps = [
  { name = "bison", version = "3.8.2", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "lz4", version = "1.10.0", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 3 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zstd", version = "1.5.7", revision = 2 },
]

[linux-amd64]
sha256 = "5d509dac0d5ab8a106e517367d9a58555031709ca2bc89fabfffcd212a325fa2"
deps = [
  { name = "bison", version = "3.8.2", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "lz4", version = "1.10.0", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 3 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zstd", version = "1.5.7", revision = 2 },
]

[linux-arm64]
sha256 = "f8b051c84be53cf978fe43cb14494d51c00233a9a982252cdb9f1d2bd948f281"
deps = [
  { name = "bison", version = "3.8.2", revision = 2 },
  { name = "cmake", version = "4.3.3", revision = 2 },
  { name = "lz4", version = "1.10.0", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 3 },
  { name = "pcre2", version = "10.47", revision = 2 },
  { name = "xz", version = "5.8.3", revision = 2 },
  { name = "zstd", version = "1.5.7", revision = 2 },
]
