[package]
name = "mdbook"
version = "0.5.4"
revision = 2
description = "Create modern online books from Markdown files"
license = "MPL-2.0"
homepage = "https://rust-lang.github.io/mdBook/"

[source]
repo = "rust-lang/mdBook"
url = "https://github.com/rust-lang/mdBook/archive/refs/tags/v0.5.4.tar.gz"
sha256 = "107614330c35c77d53b6f6ce7826c50eed087650efe5646a4d0a16ca6bf5544b"
released_at = "2026-07-06"

[build]
steps = [
  "cargo install --path . --root ${PREFIX}",
]

[dependencies]
build = ["rust"]

[smoke]
commands = [
  "${PREFIX}/bin/mdbook --version",
]
