[package]
name = "mdbook"
version = "0.5.3"
description = "Create modern online books from Markdown files"
license = "MPL-2.0"
homepage = "https://rust-lang.github.io/mdBook/"

[source]
repo = "rust-lang/mdBook"
url = "https://github.com/rust-lang/mdBook/archive/refs/tags/v0.5.3.tar.gz"
sha256 = "7c3e2907c0482fc9721a46ac42d7954600d795ce2152bed418553999ec1ee8f1"
released_at = "2026-05-19"

[build]
steps = [
  "cargo install --path . --root ${PREFIX}",
]

[dependencies]
build = ["rust"]

[smoke]
commands = [
  "${PREFIX}/bin/mdbook --version",
]
