version = "1.6.1-2"

[darwin-arm64]
sha256 = "8645e3d6a88c504eddf4f2da5a20acca93b32433adb5e719d0f957e545325e71"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.1", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.2", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-amd64]
sha256 = "8456e197de40b1c7fd1c7a4360260e49659e87cc3d270bd0346f61745bf69db5"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.1", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.2", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-arm64]
sha256 = "ea16fb5a6f3fed71c88e50861735adc5961091ee34dda77e3f04001041bb3943"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.1", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.2", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]
