[package]
name = "jq"
version = "1.8.1"
description = "Lightweight and flexible command-line JSON processor"
license = "MIT"
homepage = "https://jqlang.github.io/jq"

[source]
repo = "jqlang/jq"
url = "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-1.8.1.tar.gz"
sha256 = "2be64e7129cecb11d5906290eba10af694fb9e3e7f9fc208a311dc33ca837eb0"
released_at = "2025-07-01"

[build]
steps = [
  "./configure --prefix=${PREFIX} --with-oniguruma=builtin --disable-docs --disable-maintainer-mode --disable-shared --enable-all-static",
  "make -j${JOBS}",
  "make install",
]

[dependencies]
build = ["autoconf", "automake", "libtool"]

[binary.linux-amd64]
url = "https://ghcr.io/v2/kelp/gale-recipes/jq/blobs/sha256:895b6ea0f8af6c892d7d51fd55e9d457b39ef537dda56583c61e5bdd8096a5ae"
sha256 = "895b6ea0f8af6c892d7d51fd55e9d457b39ef537dda56583c61e5bdd8096a5ae"



[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/jq/blobs/sha256:557ea474cf791d17d718067600c3e89a1ac9d8901609c79708a2eed279fb4aa6"
sha256 = "557ea474cf791d17d718067600c3e89a1ac9d8901609c79708a2eed279fb4aa6"
