[package]
name = "jq"
version = "1.8.1"
description = "Lightweight and flexible command-line JSON processor"
license = "MIT"
homepage = "https://jqlang.github.io/jq"

[source]
repo = "jqlang/jq"
url = "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-1.8.1.tar.gz"
sha256 = "2be64e7129cecb11d5906290eba10af694fb9e3e7f9fc208a311dc33ca837eb0"
released_at = "2025-07-01"

[build]
steps = [
  "./configure --prefix=${PREFIX} --with-oniguruma=builtin --disable-docs --disable-maintainer-mode",
  "make -j${JOBS}",
  "make install",
]

[dependencies]
build = []

[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/jq/blobs/sha256:baf21f37b6e6a9f894158835371187cff881694224265278ac7b65eab5909c49"
sha256 = "baf21f37b6e6a9f894158835371187cff881694224265278ac7b65eab5909c49"

[binary.linux-amd64]
url = "https://ghcr.io/v2/kelp/gale-recipes/jq/blobs/sha256:273e96c43b9a490d99f703fb942291d36450c2b42cf8fd762bef40b3ce5cae7a"
sha256 = "273e96c43b9a490d99f703fb942291d36450c2b42cf8fd762bef40b3ce5cae7a"
