[package]
name = "gale"
version = "0.10.4"
description = "Package manager that replaces Homebrew, Nix, and home-manager"
license = "MIT"
homepage = "https://github.com/kelp/gale"

[source]
repo = "kelp/gale"
url = "https://github.com/kelp/gale/archive/refs/tags/v0.10.4.tar.gz"
sha256 = "91e5e17a24acd92f20287742183b66e5dab5bc3f93ccedd4a8ccea20505c096e"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin ${PREFIX}/man/man1",
  "go build -ldflags \"-X main.version=v${VERSION}\" -o ${PREFIX}/bin/gale ./cmd/gale/",
  "cp gale.1 ${PREFIX}/man/man1/",
]
