[package]
name = "gale"
version = "0.16.1"
description = "Package manager that replaces Homebrew, Nix, and home-manager"
license = "MIT"
homepage = "https://github.com/kelp/gale"

[source]
repo = "kelp/gale"
url = "https://github.com/kelp/gale/archive/refs/tags/v0.16.1.tar.gz"
sha256 = "72f0697e6e68fb19d0158912a025a077e5d0867164b7a6391203a60143f3b886"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin ${PREFIX}/man/man1",
  "go build -ldflags \"-X main.version=v${VERSION}\" -o ${PREFIX}/bin/gale ./cmd/gale/",
  "cp gale.1 ${PREFIX}/man/man1/",
]
