[package]
name = "gale"
version = "0.12.2"
description = "Package manager that replaces Homebrew, Nix, and home-manager"
license = "MIT"
homepage = "https://github.com/kelp/gale"

[source]
repo = "kelp/gale"
url = "https://github.com/kelp/gale/archive/refs/tags/v0.12.2.tar.gz"
sha256 = "d71dea6e634df7c2beb7ffa6d3c31238b702684b173686e5d0220da6c055028f"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin ${PREFIX}/man/man1",
  "go build -ldflags \"-X main.version=v${VERSION}\" -o ${PREFIX}/bin/gale ./cmd/gale/",
  "cp gale.1 ${PREFIX}/man/man1/",
]
