[package]
name = "gh"
version = "2.92.0"
revision = 2
description = "GitHub command-line tool"
license = "MIT"
homepage = "https://cli.github.com/"

[source]
repo = "cli/cli"
url = "https://github.com/cli/cli/archive/refs/tags/v2.92.0.tar.gz"
sha256 = "ad18928ce4e2695d7fc1adefa0f5e0496e570a430016cee4c22d7bf87e5d9c1d"
released_at = "2026-04-28"

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -trimpath -ldflags \"-X github.com/cli/cli/v2/internal/build.Version=v2.89.0 -X github.com/cli/cli/v2/internal/build.Date=2026-03-26\" -o ${PREFIX}/bin/gh ./cmd/gh",
]

[dependencies]
build = ["go"]
