[package]
name = "glances"
version = "4.5.5"
revision = 3
description = "A cross-platform curses-based monitoring tool"
license = "LGPL-3.0-only"
homepage = "http://nicolargo.github.io/glances/"

[source]
repo = "nicolargo/glances"
url = "https://github.com/nicolargo/glances/archive/refs/tags/v4.5.5.tar.gz"
sha256 = "0d67ee3571b25166641d93dfb2605a98b15d5b1bdbbcbf112f39e49f5501148d"
released_at = "2026-06-13"

[build]
system = "python"
steps = [
  "${DEP_PYTHON}/bin/python3 -m pip install --prefix=${PREFIX} --no-deps .",
]

[dependencies]
build = ["python"]