[package]
name = "glances"
version = "4.5.6"
revision = 3
description = "A cross-platform curses-based monitoring tool"
license = "LGPL-3.0-only"
homepage = "http://nicolargo.github.io/glances/"

[source]
repo = "nicolargo/glances"
url = "https://github.com/nicolargo/glances/archive/refs/tags/v4.5.6.tar.gz"
sha256 = "1ef1700bfac5bf491e42df5840448de3f699752eeebba5bc9402ce847213a888"
released_at = "2026-08-01"

[build]
system = "python"
steps = [
  "${DEP_PYTHON}/bin/python3 -m pip install --prefix=${PREFIX} --no-deps .",
]

[dependencies]
build = ["python"]