[package]
name = "golangci-lint"
version = "2.12.2"
revision = 2
description = "Fast Go linters runner"
license = "GPL-3.0"
homepage = "https://golangci-lint.run"

[source]
repo = "golangci/golangci-lint"
url = "https://github.com/golangci/golangci-lint/archive/refs/tags/v2.12.2.tar.gz"
sha256 = "568cfb0ad40832177826608003065a976254415509dd8b4e3ba19ee586388b94"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -o ${PREFIX}/bin/golangci-lint ./cmd/golangci-lint/",
]
