[package]
name = "golangci-lint"
version = "2.11.4"
description = "Fast Go linters runner"
license = "GPL-3.0"
homepage = "https://golangci-lint.run"

[source]
repo = "golangci/golangci-lint"
url = "https://github.com/golangci/golangci-lint/archive/refs/tags/v2.11.4.tar.gz"
sha256 = "388dc80d6bd01417144c2bad2b21f58fc069f66bb91f63c111b5e826e67d240a"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -o ${PREFIX}/bin/golangci-lint ./cmd/golangci-lint/",
]

[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/golangci-lint/blobs/sha256:4dbc2479378790f4984332198f1c69aecd25ec2b8d1d755bd26c2a9ddecb1667"
sha256 = "4dbc2479378790f4984332198f1c69aecd25ec2b8d1d755bd26c2a9ddecb1667"

[binary.linux-amd64]
url = "https://ghcr.io/v2/kelp/gale-recipes/golangci-lint/blobs/sha256:f4ea037b9c9cfa886adc1755996c6002aeaefeeea9132f272c486a6f08bec635"
sha256 = "f4ea037b9c9cfa886adc1755996c6002aeaefeeea9132f272c486a6f08bec635"
