version = "563.0.0"

[darwin-arm64]
sha256 = "e85b62b05b79e558b20d152bbabd4b86d3d9c130dd4bef2e3ec82241d749cca7"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.1", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.2", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-amd64]
sha256 = "43e335808afe71bed6390e5814f54c969b904c2052cf0f8228a7055690d88376"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.1", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.2", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-arm64]
sha256 = "48116779dd8fec3fdac094b7aa2d0c989afeda2f1d81bf1fd88f91501df8d687"
deps = [
  { name = "bzip2", version = "1.0.8", revision = 2 },
  { name = "cmake", version = "4.3.1", revision = 2 },
  { name = "libffi", version = "3.5.2", revision = 2 },
  { name = "ncurses", version = "6.4", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "python", version = "3.14.4", revision = 3 },
  { name = "readline", version = "8.2", revision = 2 },
  { name = "sqlite", version = "3.48.0", revision = 2 },
  { name = "xz", version = "5.8.2", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]
