version = "1.20.1-2"

[darwin-arm64]
sha256 = "ad58035d9677c5a550dc417e89be85022a436210480afcdd76b881a39ded7216"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-amd64]
sha256 = "9abf1578888b05dd558f89d3aea2b24f58c17f1e1b82689b6d0f6fd62a260ae8"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-arm64]
sha256 = "cc89ccedc3abdbd6c0526f081858f6530a51ca2bc91de7ad88b3d1a7a6e1e507"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "rust", version = "1.95.0", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]
