"""Darwin/arm64 admit inputs for the fetch catalog.

Argv only. gale admit on a Darwin host still has to
print tree_digest. Do not invent hashes here.

PACKAGES is the Darwin admit list. Names already on
INDEX_BASE are skipped by admit_darwin.py. After a
wave, drop omitted names so later CI is not red.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Package:
    name: str
    version: str
    description: str
    license: str
    homepage: str
    repo: str
    url: str
    format: str
    strip: int
    hash_source: str
    sha256: str
    files: tuple[str, ...]
    os: str = "darwin"
    arch: str = "arm64"


PACKAGES: tuple[Package, ...] = (
    Package(
        name="jq",
        version="1.8.2",
        description="Lightweight and flexible command-line JSON processor",
        license="MIT",
        homepage="https://jqlang.github.io/jq",
        repo="jqlang/jq",
        url="https://github.com/jqlang/jq/releases/download/jq-1.8.2/jq-macos-arm64",
        format="binary",
        strip=0,
        hash_source="upstream-sha256sums",
        sha256="2d75340ba57a4b4b4c8708a21c2dc8e958a48aaa8bba13b27f77f6e4c0eca07e",
        files=("jq-macos-arm64:bin/jq:755",),
    ),
    Package(
        name="ripgrep",
        version="15.2.0",
        description="Search tool like grep and The Silver Searcher",
        license="Unlicense",
        homepage="https://github.com/BurntSushi/ripgrep",
        repo="BurntSushi/ripgrep",
        url="https://github.com/BurntSushi/ripgrep/releases/download/15.2.0/ripgrep-15.2.0-aarch64-apple-darwin.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="3750b2e93f37e0c692657da574d7019a101c0084da05a790c83fd335bad973e4",
        files=("rg:bin/rg:755",),
    ),
    Package(
        name="fd",
        version="10.4.2",
        description="Simple, fast and user-friendly alternative to find",
        license="Apache-2.0",
        homepage="https://github.com/sharkdp/fd",
        repo="sharkdp/fd",
        url="https://github.com/sharkdp/fd/releases/download/v10.4.2/fd-v10.4.2-aarch64-apple-darwin.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="computed",
        sha256="",
        files=("fd:bin/fd:755",),
    ),
    Package(
        name="just",
        version="1.58.0",
        description="Handy way to save and run project-specific commands",
        license="CC0-1.0",
        homepage="https://github.com/casey/just",
        repo="casey/just",
        url="https://github.com/casey/just/releases/download/1.58.0/just-1.58.0-aarch64-apple-darwin.tar.gz",
        format="tar.gz",
        strip=0,
        hash_source="upstream-sha256sums",
        sha256="50ae3e996c974a0bf32ea7d10f495070df33f1b43e0616b2769e3d4821ed8f48",
        files=("just:bin/just:755",),
    ),
    Package(
        name="gh",
        version="2.98.0",
        description="GitHub command-line tool",
        license="MIT",
        homepage="https://cli.github.com/",
        repo="cli/cli",
        url="https://github.com/cli/cli/releases/download/v2.98.0/gh_2.98.0_macOS_arm64.zip",
        format="zip",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="8cfb027cc5310675f2b830eac8f9865c1155a45ffcf9757f699fdd5a22046ca4",
        files=("bin/gh:bin/gh:755",),
    ),
    Package(
        name="direnv",
        version="2.37.1",
        description="Per-directory environment variables",
        license="MIT",
        homepage="https://direnv.net",
        repo="direnv/direnv",
        url="https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.darwin-arm64",
        format="binary",
        strip=0,
        hash_source="computed",
        sha256="",
        files=("direnv.darwin-arm64:bin/direnv:755",),
    ),
    Package(
        name="gofumpt",
        version="0.11.0",
        description="Stricter gofmt",
        license="BSD-3-Clause",
        homepage="https://github.com/mvdan/gofumpt",
        repo="mvdan/gofumpt",
        url="https://github.com/mvdan/gofumpt/releases/download/v0.11.0/gofumpt_v0.11.0_darwin_arm64",
        format="binary",
        strip=0,
        hash_source="computed",
        sha256="",
        files=("gofumpt_v0.11.0_darwin_arm64:bin/gofumpt:755",),
    ),
    Package(
        name="golangci-lint",
        version="2.13.1",
        description="Fast Go linters runner",
        license="GPL-3.0",
        homepage="https://golangci-lint.run",
        repo="golangci/golangci-lint",
        url="https://github.com/golangci/golangci-lint/releases/download/v2.13.1/golangci-lint-2.13.1-darwin-arm64.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="0c9818baf6fb8ad26c6d2ef51b68d5a1e260ef07727036b1431647cc44637c7c",
        files=("golangci-lint:bin/golangci-lint:755",),
    ),
    Package(
        name="go",
        version="1.26.1",
        description="The Go programming language",
        license="BSD-3-Clause",
        homepage="https://go.dev",
        repo="golang/go",
        url="https://go.dev/dl/go1.26.1.darwin-arm64.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="353df43a7811ce284c8938b5f3c7df40b7bfb6f56cb165b150bc40b5e2dd541f",
        files=(
            "bin:bin:755",
            "src:src:755",
            "pkg:pkg:755",
            "lib:lib:755",
            "api:api:755",
            "doc:doc:755",
            "misc:misc:755",
            "test:test:755",
            "VERSION:VERSION:644",
            "LICENSE:LICENSE:644",
            "PATENTS:PATENTS:644",
            "README.md:README.md:644",
            "CONTRIBUTING.md:CONTRIBUTING.md:644",
            "SECURITY.md:SECURITY.md:644",
            "go.env:go.env:644",
            "codereview.cfg:codereview.cfg:644",
        ),
    ),
    Package(
        name="uv",
        version="0.12.5",
        description="Extremely fast Python package installer and resolver, written in Rust",
        license="Apache-2.0",
        homepage="https://docs.astral.sh/uv/",
        repo="astral-sh/uv",
        url="https://github.com/astral-sh/uv/releases/download/0.12.5/uv-aarch64-apple-darwin.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="5bb0e5fe008a773c3dbcb97ff79cd89e1241464fe9d2f986d52ad8f1b037bd62",
        files=("uv:bin/uv:755", "uvx:bin/uvx:755"),
    ),
    Package(
        name="fzf",
        version="0.74.3",
        description="Command-line fuzzy finder written in Go",
        license="MIT",
        homepage="https://github.com/junegunn/fzf",
        repo="junegunn/fzf",
        url="https://github.com/junegunn/fzf/releases/download/v0.74.3/fzf-0.74.3-darwin_arm64.tar.gz",
        format="tar.gz",
        strip=0,
        hash_source="upstream-sha256sums",
        sha256="1f8501cea4f9c0c2d6110d0ff75d0ec9451cd9d7524d9a26244a154ea89f3bd5",
        files=("fzf:bin/fzf:755",),
    ),
    Package(
        name="age",
        version="1.3.1",
        description="Simple, modern, secure file encryption",
        license="BSD-3-Clause",
        homepage="https://github.com/FiloSottile/age",
        repo="FiloSottile/age",
        url="https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-darwin-arm64.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="computed",
        sha256="",
        files=("age:bin/age:755", "age-keygen:bin/age-keygen:755"),
    ),
    Package(
        name="shfmt",
        version="3.13.1",
        description="Autoformat shell script source code",
        license="BSD-3-Clause",
        homepage="https://github.com/mvdan/sh",
        repo="mvdan/sh",
        url="https://github.com/mvdan/sh/releases/download/v3.13.1/shfmt_v3.13.1_darwin_arm64",
        format="binary",
        strip=0,
        hash_source="computed",
        sha256="",
        files=("shfmt_v3.13.1_darwin_arm64:bin/shfmt:755",),
    ),
    Package(
        name="actionlint",
        version="1.7.12",
        description="Static checker for GitHub Actions workflow files",
        license="MIT",
        homepage="https://github.com/rhysd/actionlint",
        repo="rhysd/actionlint",
        url="https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_darwin_arm64.tar.gz",
        format="tar.gz",
        strip=0,
        hash_source="upstream-sha256sums",
        sha256="aba9ced2dee8d27fecca3dc7feb1a7f9a52caefa1eb46f3271ea66b6e0e6953f",
        files=("actionlint:bin/actionlint:755",),
    ),
    Package(
        name="yq",
        version="4.53.6",
        description="Process YAML, JSON, XML, CSV and properties documents from the CLI",
        license="MIT",
        homepage="https://github.com/mikefarah/yq",
        repo="mikefarah/yq",
        url="https://github.com/mikefarah/yq/releases/download/v4.53.6/yq_darwin_arm64",
        format="binary",
        strip=0,
        hash_source="computed",
        sha256="",
        files=("yq_darwin_arm64:bin/yq:755",),
    ),
    Package(
        name="shellcheck",
        version="0.11.0",
        description="Static analysis and lint tool, for (ba)sh scripts",
        license="GPL-3.0-or-later",
        homepage="https://www.shellcheck.net/",
        repo="koalaman/shellcheck",
        url="https://github.com/koalaman/shellcheck/releases/download/v0.11.0/shellcheck-v0.11.0.darwin.aarch64.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="computed",
        sha256="",
        files=("shellcheck:bin/shellcheck:755",),
    ),
    Package(
        name="starship",
        version="1.26.0",
        description="Cross-shell prompt for astronauts",
        license="ISC",
        homepage="https://starship.rs/",
        repo="starship/starship",
        url="https://github.com/starship/starship/releases/download/v1.26.0/starship-aarch64-apple-darwin.tar.gz",
        format="tar.gz",
        strip=0,
        hash_source="upstream-sha256sums",
        sha256="c40b27b11f580411e068f2fa6c1be7830a387c0bc47a94d1d37f32b054c5361d",
        files=("starship:bin/starship:755",),
    ),
    Package(
        name="zoxide",
        version="0.10.0",
        description="Shell extension to navigate your filesystem faster",
        license="MIT",
        homepage="https://github.com/ajeetdsouza/zoxide",
        repo="ajeetdsouza/zoxide",
        url="https://github.com/ajeetdsouza/zoxide/releases/download/v0.10.0/zoxide-0.10.0-aarch64-apple-darwin.tar.gz",
        format="tar.gz",
        strip=0,
        hash_source="computed",
        sha256="",
        files=("zoxide:bin/zoxide:755",),
    ),
)


# linux/amd64 for the original ten. Same versions as
# darwin/arm64. Added as extra platforms, not new
# version blocks. musl where upstream ships it.
LINUX_PACKAGES: tuple[Package, ...] = (
    Package(
        name="jq",
        version="1.8.2",
        description="Lightweight and flexible command-line JSON processor",
        license="MIT",
        homepage="https://jqlang.github.io/jq",
        repo="jqlang/jq",
        url="https://github.com/jqlang/jq/releases/download/jq-1.8.2/jq-linux-amd64",
        format="binary",
        strip=0,
        hash_source="upstream-sha256sums",
        sha256="b1c22172dd303f3be49e935aa56aa48a8b7a46e0bc838b4997d3bb451495870f",
        files=("jq-linux-amd64:bin/jq:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="ripgrep",
        version="15.2.0",
        description="Search tool like grep and The Silver Searcher",
        license="Unlicense",
        homepage="https://github.com/BurntSushi/ripgrep",
        repo="BurntSushi/ripgrep",
        url="https://github.com/BurntSushi/ripgrep/releases/download/15.2.0/ripgrep-15.2.0-x86_64-unknown-linux-musl.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="33e15bcf1624b25cdd2a55813a47a2f95dbe126268203e76aa6a585d1e7b149c",
        files=("rg:bin/rg:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="fd",
        version="10.4.2",
        description="Simple, fast and user-friendly alternative to find",
        license="Apache-2.0",
        homepage="https://github.com/sharkdp/fd",
        repo="sharkdp/fd",
        url="https://github.com/sharkdp/fd/releases/download/v10.4.2/fd-v10.4.2-x86_64-unknown-linux-musl.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="computed",
        sha256="",
        files=("fd:bin/fd:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="just",
        version="1.58.0",
        description="Handy way to save and run project-specific commands",
        license="CC0-1.0",
        homepage="https://github.com/casey/just",
        repo="casey/just",
        url="https://github.com/casey/just/releases/download/1.58.0/just-1.58.0-x86_64-unknown-linux-musl.tar.gz",
        format="tar.gz",
        strip=0,
        hash_source="upstream-sha256sums",
        sha256="4a5cc2f53e6f0f8c59092a6cc38291eb729d46a7dd95d3ae582008881b84931d",
        files=("just:bin/just:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="gh",
        version="2.98.0",
        description="GitHub command-line tool",
        license="MIT",
        homepage="https://cli.github.com/",
        repo="cli/cli",
        url="https://github.com/cli/cli/releases/download/v2.98.0/gh_2.98.0_linux_amd64.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="3b8ac6b30336802fc1a858d7c084e11cdf24ac1a761ca90b68022d7d729208de",
        files=("bin/gh:bin/gh:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="direnv",
        version="2.37.1",
        description="Per-directory environment variables",
        license="MIT",
        homepage="https://direnv.net",
        repo="direnv/direnv",
        url="https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.linux-amd64",
        format="binary",
        strip=0,
        hash_source="computed",
        sha256="",
        files=("direnv.linux-amd64:bin/direnv:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="gofumpt",
        version="0.11.0",
        description="Stricter gofmt",
        license="BSD-3-Clause",
        homepage="https://github.com/mvdan/gofumpt",
        repo="mvdan/gofumpt",
        url="https://github.com/mvdan/gofumpt/releases/download/v0.11.0/gofumpt_v0.11.0_linux_amd64",
        format="binary",
        strip=0,
        hash_source="computed",
        sha256="",
        files=("gofumpt_v0.11.0_linux_amd64:bin/gofumpt:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="golangci-lint",
        version="2.13.1",
        description="Fast Go linters runner",
        license="GPL-3.0",
        homepage="https://golangci-lint.run",
        repo="golangci/golangci-lint",
        url="https://github.com/golangci/golangci-lint/releases/download/v2.13.1/golangci-lint-2.13.1-linux-amd64.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="b17bfbc9d4aaa48be7f4f1ce3240bc3d8200c870c072bacf15c26219e2cfb9cc",
        files=("golangci-lint:bin/golangci-lint:755",),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="go",
        version="1.26.1",
        description="The Go programming language",
        license="BSD-3-Clause",
        homepage="https://go.dev",
        repo="golang/go",
        url="https://go.dev/dl/go1.26.1.linux-amd64.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="031f088e5d955bab8657ede27ad4e3bc5b7c1ba281f05f245bcc304f327c987a",
        files=(
            "bin:bin:755",
            "src:src:755",
            "pkg:pkg:755",
            "lib:lib:755",
            "api:api:755",
            "doc:doc:755",
            "misc:misc:755",
            "test:test:755",
            "VERSION:VERSION:644",
            "LICENSE:LICENSE:644",
            "PATENTS:PATENTS:644",
            "README.md:README.md:644",
            "CONTRIBUTING.md:CONTRIBUTING.md:644",
            "SECURITY.md:SECURITY.md:644",
            "go.env:go.env:644",
            "codereview.cfg:codereview.cfg:644",
        ),
        os="linux",
        arch="amd64",
    ),
    Package(
        name="uv",
        version="0.12.5",
        description="Extremely fast Python package installer and resolver, written in Rust",
        license="Apache-2.0",
        homepage="https://docs.astral.sh/uv/",
        repo="astral-sh/uv",
        url="https://github.com/astral-sh/uv/releases/download/0.12.5/uv-x86_64-unknown-linux-musl.tar.gz",
        format="tar.gz",
        strip=1,
        hash_source="upstream-sha256sums",
        sha256="a4742988791c9aeae68c78150d6cba762062ad2a47e53738c2779d2b596bfcdb",
        files=("uv:bin/uv:755", "uvx:bin/uvx:755"),
        os="linux",
        arch="amd64",
    ),
)


def by_name(name: str) -> Package:
    for p in PACKAGES:
        if p.name == name:
            return p
    raise KeyError(name)


def admit_argv(pkg: Package, archive: str) -> list[str]:
    argv = [
        "gale", "admit",
        "--archive", archive,
        "--name", pkg.name,
        "--version", pkg.version,
        "--os", pkg.os,
        "--arch", pkg.arch,
        "--url", pkg.url,
        "--format", pkg.format,
        "--strip", str(pkg.strip),
        "--hash-source", pkg.hash_source,
    ]
    if pkg.hash_source == "upstream-sha256sums":
        argv.extend(["--sha256", pkg.sha256])
    for fe in pkg.files:
        argv.extend(["--file", fe])
    return argv


def header(pkg: Package) -> str:
    return (
        f"[package]\n"
        f'name = "{pkg.name}"\n'
        f'description = "{pkg.description}"\n'
        f'license = "{pkg.license}"\n'
        f'homepage = "{pkg.homepage}"\n'
        f'repo = "{pkg.repo}"\n'
        f'latest = "{pkg.version}"\n'
    )
