[package]
name = "ripgrep"
description = "Search tool like grep and The Silver Searcher"
license = "Unlicense"
homepage = "https://github.com/BurntSushi/ripgrep"
repo = "BurntSushi/ripgrep"
latest = "15.2.0"

[versions."15.2.0".artifacts."darwin/arm64"]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.2.0/ripgrep-15.2.0-aarch64-apple-darwin.tar.gz"
format = "tar.gz"
sha256 = "3750b2e93f37e0c692657da574d7019a101c0084da05a790c83fd335bad973e4"
tree_digest = "sha256:0cb4149ae4af98e57f9f9b9656c189ad452bfe0d5005e73037ac8316c17b3bd2"
hash_source = "upstream-sha256sums"
strip = 1

[[versions."15.2.0".artifacts."darwin/arm64".files]]
src = "rg"
dest = "bin/rg"
mode = 0o755

[versions."15.2.0".artifacts."linux/amd64"]
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.2.0/ripgrep-15.2.0-x86_64-unknown-linux-musl.tar.gz"
format = "tar.gz"
sha256 = "33e15bcf1624b25cdd2a55813a47a2f95dbe126268203e76aa6a585d1e7b149c"
tree_digest = "sha256:3caf9ae4dc51a82c6c8132599eb51278d98b913eb9d61bacc5c3694a26642864"
hash_source = "upstream-sha256sums"
strip = 1

[[versions."15.2.0".artifacts."linux/amd64".files]]
src = "rg"
dest = "bin/rg"
mode = 0o755
