[package]
name = "lazygit"
version = "0.60.0"
description = "Simple terminal UI for git commands"
license = "MIT"
homepage = "https://github.com/jesseduffield/lazygit"

[source]
repo = "jesseduffield/lazygit"
url = "https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.60.0.tar.gz"
sha256 = "c0cb64f7861e439ef13fa06845e7ab6b219364b7b083c7ff10d851e764e6b16b"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -ldflags \"-X main.version=0.60.0 -X main.buildSource=gale\" -o ${PREFIX}/bin/lazygit",
]

[binary.darwin-arm64]
url = "https://ghcr.io/v2/kelp/gale-recipes/lazygit/blobs/sha256:9b8012265d01d2b03fba022da7c62cb9bb79d831a58f1f17cf302aaf08c760dd"
sha256 = "9b8012265d01d2b03fba022da7c62cb9bb79d831a58f1f17cf302aaf08c760dd"

[binary.linux-amd64]
url = "https://ghcr.io/v2/kelp/gale-recipes/lazygit/blobs/sha256:3308d2467b4f7a39edf3d394cf74b5fec78680787d242e4b7df9e3d1d1c8b8d3"
sha256 = "3308d2467b4f7a39edf3d394cf74b5fec78680787d242e4b7df9e3d1d1c8b8d3"
