[package]
name = "lazygit"
version = "0.62.2"
revision = 2
description = "Simple terminal UI for git commands"
license = "MIT"
homepage = "https://github.com/jesseduffield/lazygit"

[source]
repo = "jesseduffield/lazygit"
url = "https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.62.2.tar.gz"
sha256 = "0bd1cdbaf1a584d2eb2fd14f068a8eaaeaeb80d3e2713c72005de9e4feaf6844"

[dependencies]
build = ["go"]

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -ldflags \"-X main.version=0.60.0 -X main.buildSource=gale\" -o ${PREFIX}/bin/lazygit",
]
