[package]
name = "libevent"
version = "2.1.12"
description = "Event notification library"
license = "BSD-3-Clause"
homepage = "https://libevent.org"

[source]
repo = "libevent/libevent"
url = "https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz"
sha256 = "92e6de1be9ec176428fd2367677e61ceffc2ee1cb119035037a27d346b0403bb"

[build]
steps = [
  "./configure --prefix=${PREFIX} --disable-openssl --disable-samples --disable-libevent-regress",
  "make -j${JOBS}",
  "make install",
]
