[package]
name = "libffi"
version = "3.6.0"
revision = 2
description = "Portable Foreign Function Interface library"
license = "MIT"
homepage = "https://sourceware.org/libffi/"

[source]
repo = "libffi/libffi"
url = "https://github.com/libffi/libffi/releases/download/v3.6.0/libffi-3.6.0.tar.gz"
sha256 = "31ff1fe32deaebfbb388727f32677bb254bf2a41382c51464c0b1837c9ee9828"
released_at = "2026-06-20"

[build]
system = "autotools"
steps = [
  "./configure --prefix=${PREFIX} --disable-docs --disable-multi-os-directory",
  "make -j${JOBS}",
  "make install",
]
