[package]
name = "libgit2"
version = "1.9.6"
revision = 3
description = "A cross-platform, linkable library implementation of Git that you can use in your application."
license = "GPL-2.0-only with linking exception"
homepage = "https://www.libgit2.org"

[source]
repo = "libgit2/libgit2"
url = "https://github.com/libgit2/libgit2/archive/refs/tags/v1.9.6.tar.gz"
sha256 = "a88a42a4ea9bdab7aa8686eead3bf7d9c6dd74529caca16ab22eaa92433d31d9"
released_at = "2026-07-18"

[build]
system = "cmake"
steps = [
  "cmake -B build -DCMAKE_INSTALL_PREFIX=${PREFIX} -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_CLI=OFF -DUSE_SSH=ON",
  "cmake --build build -j${JOBS}",
  "cmake --install build",
]

[dependencies]
build = ["cmake", "libssh2", "openssl", "pkgconf", "zlib"]
runtime = ["libssh2"]