version = "1.9.3-2"

[darwin-arm64]
sha256 = "153724e57edfbb2cb290a4520a607ff855aa435f1c1f86fe81b50bfd33ed727e"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "libssh2", version = "1.11.1", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-amd64]
sha256 = "cd449f08a7ba32de760ae47c83c392aa1a57b427ac9de2623172869600a10ad4"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "libssh2", version = "1.11.1", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]

[linux-arm64]
sha256 = "cfd5c450f063fb234e6f10906736611b302c306212c7c3842c672188daee60d3"
deps = [
  { name = "cmake", version = "4.3.2", revision = 2 },
  { name = "libssh2", version = "1.11.1", revision = 2 },
  { name = "openssl", version = "3.6.1", revision = 2 },
  { name = "pkgconf", version = "2.5.1", revision = 2 },
  { name = "zlib", version = "1.3.2", revision = 2 },
]
