[package]
name = "libusb"
version = "1.0.30"
description = "Cross-platform user-space USB device access library"
license = "LGPL-2.1-or-later"
homepage = "https://libusb.info/"

[source]
repo = "libusb/libusb"
url = "https://github.com/libusb/libusb/releases/download/v1.0.30/libusb-1.0.30.tar.bz2"
sha256 = "fea36f34f9156400209595e300840767ab1a385ede1dc7ee893015aea9c6dbaf"

[build]
steps = [
  "./configure --prefix=${PREFIX} --disable-static --disable-udev",
  "make -j${JOBS}",
  "make install",
]
