[package]
name = "lsd"
version = "1.2.0"
description = "The next gen ls command"
license = "Apache-2.0"
homepage = "https://github.com/lsd-rs/lsd"

[source]
repo = "lsd-rs/lsd"
url = "https://github.com/lsd-rs/lsd/archive/refs/tags/v1.2.0.tar.gz"
sha256 = "dae8d43087686a4a1de0584922608e9cbab00727d0f72e4aa487860a9cbfeefa"
released_at = "2025-01-15"

[build]
system = "cargo"
steps = [
  "cargo install --path . --root ${PREFIX}",
]

[dependencies]
build = ["rust"]