[package]
name = "lsof"
version = "4.99.6"
description = "Utility to list open files"
license = "lsof"
homepage = "https://github.com/lsof-org/lsof"

[source]
repo = "lsof-org/lsof"
url = "https://github.com/lsof-org/lsof/archive/refs/tags/4.99.6.tar.gz"
sha256 = "2ce65158694e9c44dfc54916f5b843d887763c03128e0a1c77d62ae106537009"
released_at = "2026-03-04"

[build.darwin-arm64]
steps = [
  "mv 00README README",
  "SDK=$(xcrun --show-sdk-path) && sed -i '' \"s|/usr/include|$SDK/usr/include|g\" lib/dialects/darwin/machine.h && LSOF_INCLUDE=$SDK/usr/include LSOF_CC=cc LSOF_CCV=cc ./Configure -n darwin",
  "make -j${JOBS}",
  "mkdir -p ${PREFIX}/bin ${PREFIX}/share/man/man8",
  "cp lsof ${PREFIX}/bin/lsof",
  "cp Lsof.8 ${PREFIX}/share/man/man8/lsof.8",
]

[build.linux-amd64]
steps = [
  "mv 00README README",
  "LSOF_CC=cc LSOF_CCV=cc ./Configure -n linux",
  "make -j${JOBS}",
  "mkdir -p ${PREFIX}/bin ${PREFIX}/share/man/man8",
  "cp lsof ${PREFIX}/bin/lsof",
  "cp Lsof.8 ${PREFIX}/share/man/man8/lsof.8",
]
