[package]
name = "lz4"
version = "1.10.0"
description = "Extremely fast compression algorithm"
license = "BSD-2-Clause"
homepage = "https://lz4.github.io/lz4/"

[source]
repo = "lz4/lz4"
url = "https://github.com/lz4/lz4/releases/download/v1.10.0/lz4-1.10.0.tar.gz"
sha256 = "537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"

[build]
system = "cmake"
steps = [
  "cmake -S build/cmake -B build -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DLZ4_BUILD_CLI=OFF -DLZ4_BUILD_LEGACY_LZ4C=OFF",
  "cmake --build build -j${JOBS}",
  "cmake --install build",
]
