[package]
name = "k9s"
version = "0.50.18"
revision = 2
description = "Kubernetes CLI To Manage Your Clusters In Style!"
license = "Apache-2.0"
homepage = "https://k9scli.io/"

[source]
repo = "derailed/k9s"
url = "https://github.com/derailed/k9s/archive/refs/tags/v0.50.18.tar.gz"
sha256 = "4a438b4bc480c05ba6f78a1573ee7e1dad7956ef3e30912ae22c744cea031f96"

[build]
steps = [
  "mkdir -p ${PREFIX}/bin",
  "go build -o ${PREFIX}/bin/k9s",
]

[dependencies]
build = ["go"]
